name: Build the Executable in Windows

on:
  push:
    branches: ["develop_workflow"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest

    env:
      QT_ROOT_DIR: ${{ github.workspace }}/qtdir/qt/6.6.1/win64_msvc2019_64

    steps:
      - uses: actions/checkout@v4

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.6.1
          dir: ${{ github.workspace }}/qtdir/
          arch: win64_msvc2019_64

      - name: Configure CMake
        run: >
          cmake -B ${{ steps.strings.outputs.build-output-dir }}
          -DCMAKE_CXX_COMPILER=cl
          -DCMAKE_C_COMPILER=cl
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_INSTALL_PREFIX=build/install
          -DCMAKE_PREFIX_PATH=${{ env.QT_ROOT_DIR }}
          -S ${{ github.workspace }}

      - name: Build
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config Release

      - name: Install
        run: cmake --install ${{ steps.strings.outputs.build-output-dir }} --config Release

      - name: Change the name of the installation folder
        run: mv build/install build/revision_assistant_app

      - name: Zip the installation
        run: tar -cvf revision_assistant_app.tar revision_assistant_app
        working-directory: build

      - name: Upload ZIP
        uses: actions/upload-artifact@v4
        with:
          name: revision_assistant_windows_x64
          path: build/revision_assistant_app.tar
