name: Build the Executable in Android

on:
  push:
    branches: ["develop_workflow_android"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-20.04

    env:
      QT_ROOT_DIR: ${{ github.workspace }}/qtdir/qt/6.6.1/android_armv7
      QT_COMPILER_DIR: ${{ github.workspace }}/qtdir/qt/6.6.1/gcc_64

    steps:
      - uses: actions/checkout@v4

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Install Qt GCC
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.6.1
          dir: ${{ github.workspace }}/qtdir/
      
      - name: Install Qt Android
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.6.1
          target: android
          arch: android_armv7
          dir: ${{ github.workspace }}/qtdir/
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
    
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
  
      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21e

      - name: Configure CMake
        run: >
          cmake -B ${{ steps.strings.outputs.build-output-dir }}
          -DCMAKE_CXX_COMPILER=g++
          -DCMAKE_C_COMPILER=gcc
          -DCMAKE_BUILD_TYPE=Debug
          -DCMAKE_INSTALL_PREFIX=build/install
          -DCMAKE_PREFIX_PATH=${{ env.QT_ROOT_DIR }}
          -S ${{ github.workspace }}

      - name: Build
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config Release
      
      - name: Upload BIN
        uses: actions/upload-artifact@v4
        with:
          name: bin
          path: ${{ env.QT_ROOT_DIR }}/bin

      - name: Android Deploy QT
        run: ${{ env.QT_ROOT_DIR }}/bin/androiddeployqt --input android-RevisionAssistantApp-deployment-settings.json --output android-build
        working-directory: ${{ steps.strings.outputs.build-output-dir }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: revision_assistant_armeabi-v7a
          path: ${{ steps.strings.outputs.build-output-dir }}/android-build/build/outputs/apk/debug/android-build-debug.apk
